insert into Genre values(null, 'Blues');
insert into Genre values(null, 'Classic Rock');
insert into Genre values(null, 'Country');
insert into Genre values(null, 'Dance');
insert into Genre values(null, 'Disco');
insert into Genre values(null, 'Funk');
insert into Genre values(null, 'Grunge');
insert into Genre values(null, 'Hip-Hop');
insert into Genre values(null, 'Jazz');
insert into Genre values(null, 'Metal');
insert into Genre values(null, 'New Age');
insert into Genre values(null, 'Oldies');
insert into Genre values(null, 'Other');
insert into Genre values(null, 'Pop');
insert into Genre values(null, 'Rhythm and Blues');
insert into Genre values(null, 'Rap');
insert into Genre values(null, 'Reggae');
insert into Genre values(null, 'Rock');
insert into Genre values(null, 'Techno');
insert into Genre values(null, 'Industrial');
insert into Genre values(null, 'Alternative');
insert into Genre values(null, 'Ska');
insert into Genre values(null, 'Death Metal');
insert into Genre values(null, 'Pranks');
insert into Genre values(null, 'Soundtrack');
insert into Genre values(null, 'Euro-Techno');
insert into Genre values(null, 'Ambient');
insert into Genre values(null, 'Trip-Hop');
insert into Genre values(null, 'Vocal');
insert into Genre values(null, 'Jazz & Funk');
insert into Genre values(null, 'Fusion');
insert into Genre values(null, 'Trance');
insert into Genre values(null, 'Classical');
insert into Genre values(null, 'Instrumental');
insert into Genre values(null, 'Acid');
insert into Genre values(null, 'House');
insert into Genre values(null, 'Game');
insert into Genre values(null, 'Sound Clip');
insert into Genre values(null, 'Gospel');
insert into Genre values(null, 'Noise');
insert into Genre values(null, 'Alternative Rock');
insert into Genre values(null, 'Bass');
insert into Genre values(null, 'Soul');
insert into Genre values(null, 'Punk');
insert into Genre values(null, 'Space');
insert into Genre values(null, 'Meditative');
insert into Genre values(null, 'Instrumental Pop');
insert into Genre values(null, 'Instrumental Rock');
insert into Genre values(null, 'Ethnic');
insert into Genre values(null, 'Gothic');
insert into Genre values(null, 'Darkwave');
insert into Genre values(null, 'Techno-Industrial');
insert into Genre values(null, 'Electronic');
insert into Genre values(null, 'Pop-Folk');
insert into Genre values(null, 'Eurodance');
insert into Genre values(null, 'Dream');
insert into Genre values(null, 'Southern Rock');
insert into Genre values(null, 'Comedy');
insert into Genre values(null, 'Cult');
insert into Genre values(null, 'Gangsta');
insert into Genre values(null, 'Top 40');
insert into Genre values(null, 'Christian Rap');
insert into Genre values(null, 'Pop/Funk');
insert into Genre values(null, 'Jungle');
insert into Genre values(null, 'Native US');
insert into Genre values(null, 'Cabaret');
insert into Genre values(null, 'New Wave');
insert into Genre values(null, 'Psychedelic');
insert into Genre values(null, 'Rave');
insert into Genre values(null, 'Showtunes');
insert into Genre values(null, 'Trailer');
insert into Genre values(null, 'Lo-Fi');
insert into Genre values(null, 'Tribal');
insert into Genre values(null, 'Acid Punk');
insert into Genre values(null, 'Acid Jazz');
insert into Genre values(null, 'Polka');
insert into Genre values(null, 'Retro');
insert into Genre values(null, 'Musical');
insert into Genre values(null, "Rock 'n' Roll");
insert into Genre values(null, 'Hard Rock');

insert into Album values(null, 'Dirty Work');
insert into Album values(null, 'Nothing Personal');
insert into Album values(null, 'Future Hearts');

insert into Artist values(null, 'All Time Low');

insert into Song values(null, '5', 'Time Bomb', 1, 1, 14, '2012', './audio/time-bomb.mp3');
insert into Song values(null, '1', 'Time Bomb', 1, 2, 14, '2009', './audio/weightless.mp3');
insert into Song values(null, '3', 'Time Bomb', 1, 3, 14, '2015', './audio/somethings-gotta-give.mp3');

insert into User values(null, 'Dardan', 'Rrafshi', 'DonColon', 'drrafshi@hotmail.de', '1234');
    
insert into Playlist values(null, 'Winter Wonder', now(), 1, 'true');
    
insert into Playback values(1, 1);
insert into Playback values(1, 2);
insert into Playback values(1, 3);

commit;
